Repository viktorsec/wedding-companion, pull requests merged in 2018-06, with the labels that each got.

#3 Add build to .gitignore
  .gitignore
  build/asset-manifest.json
  build/favicon.ico
  build/index.html
  build/manifest.json
  build/service-worker.js
  build/static/css/main.c17080f1.css
  build/static/css/main.c17080f1.css.map
  build/static/js/main.8bdd2976.js
  build/static/js/main.8bdd2976.js.map
  build/static/media/logo.5d5d9eef.svg
Labels: :computer: devops

#6 Move content from templates to components
  src/App.js
  src/App_templates.js
  src/components/Drinks.js
  src/components/Navigation.js
  src/components/Program.js
  src/components/Transport.js
Labels: very good code :pray:

#7 Update deployment instructions
  README.md
Labels: :computer: devops

#10 Fix classnames
  src/App.js
  src/components/Transport.js
Labels: bug

#11 Add program data
  src/App.js
  src/components/PhotoCard.js
  src/components/Program.js
  src/components/consts/Schedule.js
Labels: very good code :pray:

#12 Add photo competition topics
  src/components/PhotoCompetition.js
Labels: :squid: Ander The Sea

#15 Add app tutorial
  public/tutorial.png
  src/components/Gdpr.js
Labels: help wanted

#17 Move tutorial to separate screen
  src/App.css
  src/App.js
  src/components/Help.js
  src/components/Navigation.js
  src/components/consts/Schedule.js
Labels: enhancement

#22 Add Google Photos integration
  .gitignore
  README.md
  src/App.css
  src/App.js
  src/components/Gdpr.js
  src/components/Help.js
  src/components/Navigation.js
  src/components/PhotoCompetition.js
  src/components/consts/Secret.js.template
Labels: very good code :pray:

#20 Set correct favicon
  public/favicon.ico
Labels: bug

#19 Fix typos
  public/touch-icon.png
  src/components/Drinks.js
Labels: :squid: Ander The Sea, bug

#23 Fix fidget switcher padding
  src/App.js
Labels: bug

#21 Refactor navigation to let it know about location
  src/App.css
  src/App.js
  src/components/Navigation.js
Labels: very good code :pray:

#24 Enhance fidget switcher
  package.json
  src/App.css
  src/App.js
  yarn.lock
Labels: very good code :pray:
